
# SPATIO-TEMPORAL CRIME PREDICTION USING DYNAMIC MODE DECOMPOSITION (DMD) AND CONVOLUTIONAL NEURAL NETWORK LONG-SHORT TERM MEMORY (CNN-LSTM) 
## Adrian Joseph Albino, Julian Ernest Camello
### This notebook documents the implementation of our thesis paper

![Conceptual Framework](conceptual_framework.png)

# Dataset
[SF Incident Report](https://www.example.com)

In [1]:
# Load Data 
import pandas as pd
file_path = 'Police_Department_Incident_Reports__2018_to_Present.csv'
df = pd.read_csv(file_path)
df.head()

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
0,2023/03/13 11:41:00 PM,2023/03/13,23:41,2023,Monday,2023/03/13 11:41:00 PM,125373607041,1253736,230167874,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023/03/01 05:02:00 AM,2023/03/01,05:02,2023,Wednesday,2023/03/11 03:40:00 PM,125379506374,1253795,236046151,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023/03/13 01:16:00 PM,2023/03/13,13:16,2023,Monday,2023/03/13 01:17:00 PM,125357107041,1253571,220343896,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023/03/13 10:59:00 AM,2023/03/13,10:59,2023,Monday,2023/03/13 11:00:00 AM,125355107041,1253551,230174885,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023/03/14 06:44:00 PM,2023/03/14,18:44,2023,Tuesday,2023/03/14 06:45:00 PM,125402407041,1254024,230176728,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Preprocessing

## Filtering & Removing Other Columns

In [2]:
columns_to_keep = ['Incident Date', 'Latitude', 'Longitude']
df.dropna(subset=columns_to_keep, inplace=True)
df = df[columns_to_keep]
df.head()

   Incident Date   Latitude   Longitude
9     2023/03/11  37.772895 -122.454285
11    2022/06/27  37.787359 -122.408227
13    2023/03/16  37.762290 -122.401324
33    2023/03/21  37.787038 -122.418271
61    2021/08/22  37.793977 -122.429804

## Aggregating By Date

In [16]:
df['Incident Date'] = pd.to_datetime(df['Incident Date'])
crime_by_date = df.groupby(pd.Grouper(key='Incident Date', freq='D'))
crime_by_date.head()

       Incident Date   Latitude   Longitude
17982     2018-01-01  37.756167 -122.406636
78404     2018-01-01  37.773467 -122.391434
98729     2018-01-01  37.767257 -122.404750
122472    2018-01-01  37.721659 -122.467615
130417    2018-01-01  37.721367 -122.473668
...              ...        ...         ...
94436     2023-11-24  37.787872 -122.411699
94437     2023-11-24  37.759830 -122.425920
94442     2023-11-24  37.748231 -122.414919
94444     2023-11-24  37.742343 -122.491768
94447     2023-11-24  37.766674 -122.419825

[10770 rows x 3 columns]

In [14]:
specific_date = '2018-01-01'  
specific_date_data = aggregated_df.get_group(specific_date)
print(specific_date_data)

       Incident Date   Latitude   Longitude
17982     2018-01-01  37.756167 -122.406636
78404     2018-01-01  37.773467 -122.391434
98729     2018-01-01  37.767257 -122.404750
122472    2018-01-01  37.721659 -122.467615
130417    2018-01-01  37.721367 -122.473668
...              ...        ...         ...
752296    2018-01-01  37.778719 -122.414741
758037    2018-01-01  37.803727 -122.428400
764293    2018-01-01  37.729910 -122.397177
773595    2018-01-01  37.721659 -122.467615
793311    2018-01-01  37.783933 -122.412595

[521 rows x 3 columns]

## Aggregation By Cluster

In [68]:
import geopandas as gpd
sf_geojson = "SanFrancisco.Neighborhoods.json"
sf_neighborhoods = gpd.read_file(sf_geojson, driver='GeoJSON')

DAYS = 100

def count_crimes_by_neighborhood(date, crimes_group):
    crimes_group = gpd.GeoDataFrame(crimes_group, geometry=gpd.points_from_xy(crimes_group['Longitude'], crimes_group['Latitude']))
    crimes_group.crs = 'EPSG:4326'
    crimes_with_neighborhoods = gpd.sjoin(crimes_group, sf_neighborhoods, how="left", predicate="within")
    counts = crimes_with_neighborhoods.groupby('neighborhood').size()
    # Set count to 0 for neighborhoods with no crimes
    counts.fillna(0, inplace=True)
    return pd.DataFrame({'date': date, 'neighborhood': counts.index, 'crime_count': counts.values})

crime_by_cluster = []

counter = 0
for date, crimes_group in crime_by_date:
     # LIMITS THE NUMBER OF DAYS TO PROCESS
    if (counter == DAYS):
        break #
    counter += 1
    
    counts_df = count_crimes_by_neighborhood(date, crimes_group)
    crime_by_cluster.append(counts_df['crime_count'].tolist())


print(crime_by_cluster[:5])

[[16, 37, 14, 20, 11, 30, 13, 17, 24, 13, 38, 35, 30, 10, 28, 2, 13, 41, 38, 9, 9, 56, 5], [10, 26, 9, 20, 5, 6, 16, 4, 25, 10, 45, 14, 7, 6, 17, 7, 4, 44, 23, 11, 5, 38, 4], [13, 15, 9, 11, 11, 20, 15, 1, 27, 10, 23, 31, 25, 9, 12, 7, 50, 34, 18, 6, 36, 3], [14, 22, 10, 21, 17, 19, 12, 2, 18, 2, 51, 40, 11, 10, 13, 1, 10, 58, 28, 21, 6, 54, 3], [3, 30, 24, 9, 12, 8, 10, 3, 13, 9, 46, 32, 9, 15, 11, 6, 9, 50, 21, 15, 12, 53, 2]]

## Time Series Splitting

In [60]:
from math import ceil

TRAIN_PERCENT = 0.8
TEST_PERCENT = 0.2

total_length = len(crime_by_cluster)
train_data_length = ceil(total_length * TRAIN_PERCENT)
test_data_length = total_length - train_data_length

# Split the data into training and testing sets
train_data = crime_by_cluster[:train_data_length]
test_data = crime_by_cluster[train_data_length:]

print("Train data length:", len(train_data))
print("Test data length:", len(test_data))

Train data length: 80
Test data length: 20

## Dynamic Mode Decomposition

In [67]:
from pydmd import DMD
from pydmd.plotter import plot_summary

for i in range(len(train_data)):
    print(train_data[i], len(train_data[i]))

# dmd = DMD(svd_rank=12)
# dmd.fit(train_data)

# plot_summary(dmd)

[16, 37, 14, 20, 11, 30, 13, 17, 24, 13, 38, 35, 30, 10, 28, 2, 13, 41, 38, 9, 9, 56, 5] 23
[10, 26, 9, 20, 5, 6, 16, 4, 25, 10, 45, 14, 7, 6, 17, 7, 4, 44, 23, 11, 5, 38, 4] 23
[13, 15, 9, 11, 11, 20, 15, 1, 27, 10, 23, 31, 25, 9, 12, 7, 50, 34, 18, 6, 36, 3] 22
[14, 22, 10, 21, 17, 19, 12, 2, 18, 2, 51, 40, 11, 10, 13, 1, 10, 58, 28, 21, 6, 54, 3] 23
[3, 30, 24, 9, 12, 8, 10, 3, 13, 9, 46, 32, 9, 15, 11, 6, 9, 50, 21, 15, 12, 53, 2] 23
[9, 15, 13, 14, 7, 12, 5, 6, 14, 13, 38, 36, 21, 15, 16, 3, 7, 66, 32, 4, 1, 60, 5] 23
[10, 14, 18, 13, 16, 18, 8, 8, 21, 3, 38, 22, 23, 12, 15, 1, 5, 36, 14, 15, 3, 43, 6] 23
[4, 20, 8, 9, 11, 16, 15, 3, 18, 8, 34, 22, 16, 7, 13, 7, 10, 32, 13, 14, 4, 32, 5] 23
[11, 25, 12, 15, 7, 27, 16, 9, 11, 9, 31, 32, 16, 12, 22, 6, 11, 48, 7, 13, 2, 31, 6] 23
[16, 26, 11, 6, 4, 25, 15, 8, 5, 3, 36, 34, 12, 14, 8, 1, 7, 63, 23, 13, 9, 51, 3] 23
[9, 24, 16, 22, 9, 15, 13, 4, 6, 13, 44, 21, 13, 6, 16, 1, 9, 56, 28, 9, 14, 28, 6] 23
[17, 11, 4, 17, 9, 22, 14, 9, 7, 8, 44, 28, 34, 9, 13, 3, 4, 60, 25, 15, 13, 58, 7] 23
[18, 29, 12, 12, 2, 20, 6, 4, 16, 11, 29, 38, 26, 7, 19, 6, 7, 52, 28, 5, 5, 44, 7] 23
[20, 14, 8, 3, 4, 19, 4, 16, 20, 11, 27, 35, 32, 4, 16, 4, 10, 48, 12, 6, 36, 3] 22
[17, 17, 16, 8, 4, 16, 18, 16, 19, 8, 35, 19, 17, 6, 20, 2, 9, 52, 28, 8, 3, 34, 5] 23
[11, 21, 7, 12, 11, 25, 11, 9, 24, 6, 39, 18, 16, 6, 17, 3, 4, 41, 18, 14, 7, 18, 8] 23
[7, 22, 17, 20, 11, 24, 7, 5, 23, 9, 34, 18, 13, 9, 10, 4, 6, 62, 14, 16, 2, 49, 4] 23
[14, 33, 7, 18, 6, 10, 12, 7, 18, 9, 39, 30, 12, 12, 15, 4, 5, 41, 31, 7, 3, 38, 6] 23
[10, 24, 15, 12, 10, 16, 17, 10, 15, 9, 38, 28, 20, 8, 12, 15, 54, 28, 16, 7, 64, 9] 22
[5, 35, 27, 8, 2, 15, 6, 8, 10, 7, 27, 22, 20, 9, 7, 5, 4, 44, 20, 6, 6, 45, 6] 23
[7, 23, 8, 13, 3, 14, 9, 9, 13, 6, 20, 33, 30, 5, 17, 4, 3, 47, 20, 8, 4, 36, 6] 23
[16, 32, 9, 12, 10, 15, 14, 23, 19, 11, 40, 35, 15, 7, 12, 3, 7, 49, 17, 11, 3, 45, 4] 23
[9, 28, 11, 13, 6, 12, 4, 9, 19, 9, 33, 26, 14, 10, 16, 4, 17, 76, 23, 12, 15, 48, 6] 23
[7, 20, 14, 7, 6, 31, 8, 10, 22, 8, 42, 33, 8, 11, 18, 5, 8, 61, 16, 7, 40, 4] 22
[14, 28, 8, 14, 9, 23, 13, 4, 17, 11, 36, 37, 25, 11, 9, 2, 7, 54, 29, 9, 4, 49, 4] 23
[12, 29, 13, 21, 7, 33, 9, 5, 11, 14, 47, 34, 17, 13, 20, 4, 13, 60, 22, 6, 8, 44, 4] 23
[4, 21, 21, 18, 8, 11, 13, 11, 14, 11, 29, 44, 16, 11, 12, 6, 10, 48, 19, 12, 6, 55, 11] 23
[15, 19, 8, 14, 7, 9, 8, 2, 9, 13, 36, 27, 28, 8, 24, 2, 11, 50, 22, 9, 10, 42, 4] 23
[7, 14, 12, 20, 18, 15, 10, 14, 12, 12, 33, 28, 19, 11, 13, 5, 10, 63, 22, 8, 10, 36, 5] 23
[14, 13, 15, 10, 7, 18, 7, 8, 15, 7, 49, 53, 17, 2, 18, 7, 7, 48, 30, 11, 6, 41, 13] 23
[10, 18, 10, 7, 21, 23, 19, 9, 19, 12, 33, 33, 10, 6, 21, 3, 9, 69, 22, 8, 2, 39, 10] 23
[7, 20, 13, 13, 10, 26, 11, 10, 21, 9, 63, 20, 24, 12, 19, 7, 8, 59, 14, 9, 5, 59, 6] 23
[12, 28, 17, 16, 11, 18, 13, 11, 11, 4, 33, 33, 14, 5, 10, 1, 18, 64, 26, 11, 4, 36, 8] 23
[23, 23, 14, 11, 5, 12, 8, 5, 13, 11, 32, 28, 20, 6, 24, 3, 5, 51, 16, 14, 6, 35, 9] 23
[8, 18, 9, 12, 5, 11, 7, 5, 19, 4, 34, 25, 20, 10, 8, 7, 40, 14, 10, 3, 26, 1] 22
[4, 23, 9, 13, 7, 19, 10, 8, 8, 6, 40, 23, 20, 5, 15, 3, 7, 62, 16, 11, 7, 29, 5] 23
[9, 17, 14, 20, 16, 22, 7, 4, 15, 6, 38, 41, 16, 5, 7, 1, 9, 60, 44, 7, 8, 49, 2] 23
[9, 36, 7, 16, 10, 26, 10, 6, 7, 7, 33, 21, 9, 8, 8, 1, 6, 55, 33, 4, 6, 62, 3] 23
[24, 32, 16, 8, 1, 28, 15, 11, 8, 10, 34, 40, 17, 8, 15, 5, 7, 63, 15, 9, 4, 56, 3] 23
[8, 14, 10, 12, 10, 33, 8, 12, 5, 13, 51, 34, 21, 7, 17, 8, 10, 60, 26, 16, 8, 40, 3] 23
[16, 24, 22, 19, 12, 10, 6, 15, 16, 9, 40, 27, 25, 7, 19, 3, 5, 49, 22, 11, 6, 48, 2] 23
[9, 12, 12, 21, 3, 16, 4, 8, 10, 3, 27, 20, 29, 9, 12, 2, 7, 48, 19, 10, 6, 35, 2] 23
[10, 22, 4, 12, 10, 20, 6, 12, 10, 4, 42, 19, 18, 11, 15, 5, 8, 71, 22, 8, 12, 30, 3] 23
[5, 25, 5, 16, 7, 12, 14, 9, 9, 12, 47, 11, 17, 7, 9, 4, 6, 38, 19, 8, 3, 48, 6] 23
[7, 31, 7, 15, 7, 14, 2, 6, 15, 10, 68, 35, 17, 5, 10, 7, 8, 58, 15, 10, 3, 47, 3] 23
[19, 27, 6, 8, 10, 13, 13, 3, 10, 14, 40, 29, 18, 8, 17, 3, 12, 59, 18, 10, 7, 68, 2] 23
[9, 20, 19, 19, 10, 8, 9, 10, 17, 10, 33, 15, 17, 13, 5, 3, 8, 52, 21, 4, 9, 37, 5] 23
[3, 15, 12, 12, 15, 14, 13, 21, 17, 16, 45, 21, 36, 6, 22, 2, 4, 35, 16, 15, 12, 49, 7] 23
[4, 26, 12, 16, 6, 14, 10, 7, 19, 13, 41, 23, 19, 6, 14, 2, 8, 35, 16, 2, 9, 40, 2] 23
[10, 23, 11, 21, 11, 10, 3, 17, 4, 33, 23, 17, 7, 12, 14, 53, 10, 8, 10, 43, 5] 21
[9, 17, 13, 14, 9, 24, 10, 8, 10, 1, 37, 20, 10, 5, 21, 4, 9, 71, 32, 9, 12, 44, 5] 23
[8, 27, 10, 16, 5, 24, 8, 6, 11, 3, 41, 48, 12, 8, 21, 3, 12, 54, 21, 7, 12, 48, 4] 23
[12, 25, 13, 12, 14, 14, 7, 8, 22, 7, 41, 35, 19, 7, 12, 5, 5, 66, 19, 3, 6, 63] 22
[16, 12, 17, 8, 8, 17, 14, 3, 6, 18, 51, 31, 17, 6, 6, 3, 7, 52, 21, 4, 9, 61, 3] 23
[9, 13, 5, 12, 15, 15, 13, 5, 13, 14, 22, 30, 25, 10, 13, 9, 19, 57, 22, 20, 9, 52, 5] 23
[14, 18, 14, 18, 4, 11, 17, 3, 17, 9, 44, 43, 20, 7, 10, 5, 5, 51, 17, 11, 11, 37, 5] 23
[9, 20, 6, 14, 7, 17, 13, 8, 17, 13, 46, 25, 21, 4, 10, 4, 3, 45, 16, 7, 7, 35, 7] 23
[11, 27, 7, 9, 7, 26, 7, 11, 7, 6, 34, 19, 9, 2, 11, 4, 9, 52, 27, 5, 15, 52, 2] 23
[12, 21, 17, 9, 7, 27, 11, 11, 17, 12, 33, 16, 16, 5, 14, 5, 7, 57, 16, 14, 9, 59, 13] 23
[9, 23, 15, 6, 18, 16, 12, 14, 13, 4, 33, 30, 14, 6, 18, 4, 11, 61, 22, 10, 14, 65, 1] 23
[6, 14, 11, 5, 6, 17, 7, 5, 17, 10, 44, 19, 19, 9, 13, 2, 6, 46, 31, 12, 9, 52, 5] 23
[12, 16, 16, 8, 2, 13, 3, 4, 18, 11, 30, 32, 28, 9, 7, 10, 6, 62, 9, 20, 10, 39, 4] 23
[9, 18, 15, 12, 7, 12, 15, 8, 8, 14, 45, 31, 11, 10, 6, 8, 67, 19, 7, 6, 39] 21
[16, 16, 8, 10, 10, 20, 7, 5, 4, 6, 31, 28, 14, 15, 19, 3, 10, 51, 19, 10, 7, 45, 3] 23
[11, 15, 3, 9, 8, 18, 6, 9, 14, 11, 32, 18, 11, 8, 47, 1, 5, 56, 9, 12, 10, 31, 6] 23
[5, 18, 10, 19, 2, 20, 6, 15, 11, 5, 32, 23, 17, 4, 86, 2, 6, 71, 19, 17, 2, 42, 4] 23
[8, 29, 17, 7, 11, 15, 16, 3, 6, 8, 38, 16, 14, 6, 21, 5, 58, 22, 11, 8, 40, 9] 22
[7, 27, 9, 8, 6, 21, 6, 8, 34, 10, 50, 22, 17, 11, 23, 1, 5, 51, 16, 12, 9, 37, 5] 23
[11, 17, 19, 9, 4, 18, 6, 3, 13, 12, 28, 28, 26, 7, 34, 5, 7, 66, 22, 7, 7, 53, 3] 23
[7, 7, 14, 9, 3, 8, 6, 3, 9, 8, 29, 16, 11, 6, 17, 2, 7, 42, 15, 8, 4, 36, 3] 23
[10, 25, 12, 22, 4, 17, 7, 15, 7, 3, 43, 26, 16, 5, 10, 2, 6, 53, 17, 5, 7, 22, 7] 23
[8, 26, 8, 12, 10, 16, 3, 7, 25, 11, 38, 29, 18, 12, 10, 9, 47, 24, 10, 7, 40, 4] 22
[17, 21, 19, 6, 8, 21, 17, 7, 18, 4, 38, 21, 6, 9, 15, 10, 52, 34, 7, 6, 47, 2] 22
[18, 16, 16, 7, 11, 18, 8, 4, 15, 10, 29, 32, 30, 5, 12, 6, 13, 46, 19, 7, 10, 32, 5] 23
[13, 18, 18, 12, 17, 11, 4, 12, 9, 9, 44, 34, 29, 9, 10, 1, 17, 53, 30, 9, 10, 34, 6] 23
[12, 19, 15, 16, 4, 6, 8, 5, 10, 13, 42, 45, 18, 5, 6, 1, 6, 71, 16, 10, 10, 29, 1] 23
[15, 21, 9, 12, 4, 11, 4, 10, 10, 7, 32, 28, 16, 10, 20, 2, 10, 60, 17, 12, 8, 48, 2] 23
[10, 16, 13, 6, 13, 20, 10, 9, 18, 5, 36, 24, 19, 3, 16, 5, 7, 50, 15, 5, 16, 43, 5] 23
[12, 19, 12, 11, 10, 13, 18, 11, 8, 3, 23, 26, 15, 4, 9, 1, 8, 51, 23, 4, 2, 45, 5] 23
[6, 16, 8, 15, 2, 11, 11, 8, 24, 5, 37, 24, 15, 4, 7, 2, 8, 55, 19, 7, 7, 31, 6] 23